# Yarn configuration file with optimized settings

# Enable Plug'n'Play for better performance
pnpMode: loose

# Network settings
httpTimeout: 60000
networkConcurrency: 8
networkTimeout: 60000

# Cache settings
enableGlobalCache: false
cacheFolder: ./.yarn/cache

# Dependency resolution settings
checksumBehavior: update

# Build settings
enableTelemetry: false

# Security settings
enableStrictSsl: true

# Miscellaneous settings
enableProgressBars: true
enableTimers: true
preferInteractive: true

# Package settings
nmMode: hardlinks-local